apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv001
  namespace: kube-logging
spec:
  capacity:
    storage: 100Gi
  storageClassName: do-block-storage
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ubuntu"
